// let numri1 = prompt("Shkruaj numrin e pare");
// let operatori = prompt("Shkruaj operatorin");
// let numri2 = prompt("Shkruaj numrin e dyte");

// console.log(numri1);
// console.log(operatori);
// console.log(numri2);

// alert(numri1 + numri2);
// alert(numri1 - numri2);
// alert(numri1 * numri2);
// alert(numri1 / numri2);
// alert(numri1 ** numri2);


// alert('mirejta')

// let numri1 =  +prompt("shkruaj numrin e pare");
// let operatorin =  prompt("shkruaj operatorin");
// let numri2 = +prompt("shkruaj numrin e dyte");
// if (operatorin == '+' ) {
//     alert(numri1 + numri2)
// }
// if (operatorin == '-' ) {
//     alert(numri1 - numri2)
// }
// if (operatorin == '*' ) {
//     alert(numri1 * numri2)
// }
// if (operatorin == '/' ) {
//     alert(numri1 / numri2)
// }
