// let x = 4 + 4;
// operatoret unar 
// let nunri1 = -4;
//console.log(numri1);
//e shendrron vleren ne numer
// let numri2 = +"4";
// let numri3 = +false;
// let numri = 0;
//likrement rritje 
// console.log("Rreshti nr 10 ", ++numri);
// console.log("Rreshti nr 11 ", numri++);
// console.log("Rreshti nr 12 ", numri);
//dekrement = zbritje 
// console.log("Rreshti nr 17 ", --numri);
// console.log("Rreshti nr 18 ", numri--);
// console.log("Rreshti nr 20 ", numri);

// let bora = confirm("a po bjen bore")

// if (bora == true) {
//     alert("Bardh rri ne shpi");
// }

// let notaMatematike = prompt("Shkruani noten ne matematike")
// if (notaMatematike >= 2 && notaMatematike <= 5){
//     alert("keni kalu")
// } else if (notaMatematike < 2 && notaMatematike > 0) {
//     alert("nuk keni kalu")
// } else if (notaMatematike < 1) {
//     alert("nota eshte gabim shkruani perseri");
//     notaMatematike = prompt("shkruaj noten perseri");
// } else {
//     alert("dicka shkoi gabim");
// }

// console.log(notaMatematike);

let mosha  = prompt("Shkruaj moshen")
if (mosha >=1 && mosha <=18){
    alert("ti je i mitur")
}

else if (mosha >=18 && mosha <=65){
    alert("ti je i rritur")
}

else if (mosha >=65 && mosha <=120){
    alert("ti je i moshuar")
}
else{
    alert('gabim')
}




    


















